# pytorch_lightning==1.8.6
seed_everything: 0

trainer:
  max_epochs: 40
  accelerator: gpu
  strategy: ddp_find_unused_parameters_true
  sync_batchnorm: True
  logger: False
  callbacks:
    - class_path: pytorch_lightning.callbacks.model_checkpoint.ModelCheckpoint
      init_args:
        dirpath: "checkpoints/"
        filename: "boundary_cityscapes_adapter"
        every_n_epochs: 10

model:
  dinov2_vit_model: "vits14"
  use_adapter: true
  use_deformable: true
  adapter_reduction: 0.25
  mode: "direct"
  head: "mlp"
  neighbor_radius: 1.5
  threshold_boundary: 0.93
  num_boundary_neighbors: 1
  test_output_size: [1024, 2048]
  test_multi_scales: [3, 4, 5]
  test_plot: False

data:
  class_path: datasets.cityscapes.CityscapesDataModule
  init_args:
    cfg_dataset:
      name: "cityscapes"
      path: "/work/dlclarge2/biswass-spino/cityscapes"
      feed_img_size: [1024, 2048]
      offsets: [0]
      remove_classes: []
    num_classes: 19
    batch_size: 1
    num_workers: 1
    transform_train:
      - class_path: utils.transforms.ToTensor
      - class_path: utils.transforms.RandomHorizontalFlip
      - class_path: utils.transforms.RandomResizedCrop
        init_args:
          size: [504, 1008]
          scale: [0.4, 1.0]
      - class_path: utils.transforms.ColorJitter
        init_args:
          brightness: 0.2
          contrast: 0.2
          saturation: 0.2
          hue: 0.2
      - class_path: utils.transforms.MaskPostProcess
      - class_path: utils.transforms.ImageNormalize
        init_args:
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
    transform_test:
      - class_path: utils.transforms.ToTensor
      - class_path: utils.transforms.Resize
        init_args:
          size: [504, 1008]
      - class_path: utils.transforms.MaskPostProcess
      - class_path: utils.transforms.ImageNormalize
        init_args:
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
    label_mode: "cityscapes_19"
    train_sample_indices: [12, 324, 450, 608, 742, 768, 798, 836, 1300, 2892]
    test_sample_indices: null

data_params:
  image_size_original: [1024, 2048]
  image_size_input: [504, 1008]
  image_mean: [0.485, 0.456, 0.406]
  image_std: [0.229, 0.224, 0.225]

ckpt_path: null

optimizer:
  class_path: torch.optim.Adam
  init_args:
    lr: 0.001

lr_scheduler:
  class_path: torch.optim.lr_scheduler.CosineAnnealingLR
  init_args:
    T_max: 40